---
title: "part II"
date: "5/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

``` {r}
library(tidyverse)
library(zoo)
library(infer)
options(scipen = "999")

df <- read_csv("Oscars-demographics-DFE.csv") %>%
  mutate_if(is.character, factor)

skimr::skim(df)

```

```{r}
# one way to answer - Which movie(s) won the most unique "Big 5" awards?
head(sort(table(df$movie), decreasing = TRUE))

```



```{r}
# second dplyr way to answer - Which movie(s) won the most unique "Big 5" awards?
df %>%
    count(movie, person,sort = TRUE)

df %>%
  filter(person == "Hilary Swank") %>%
  count(movie, person, sort = TRUE)


df %>%
  separate(birthplace, c("city", "country_state"), sep = ",") %>%
  count(country_state, sort = TRUE) %>%
  ggplot(aes(n, country_state,)) +
  geom_col()

df %>%
  separate(birthplace, c("country", "state_count"), sep = ",") %>%
  count(state_count, sort = TRUE) %>%
  mutate(state_count = fct_reorder(state_count, n)) %>%
  filter(n > 10) %>%
  ggplot(aes(n, state_count,)) +
  geom_col()


```



```{r}
# Of all actresses who have won the Best Actress award, what are is the most common first name?
df %>%
  filter(award == "Best Actress") %>%
  separate(person,
           c("first", "last")) %>%
  count(movie,first, sort = TRUE) %>%
  mutate(first = fct_reorder(first,n)) %>%
  ggplot(aes(n, first)) +
  geom_col()
```




#NA value is New York City
```{r}
#What US State, or non-US country, has produced the most Oscar winners (for the awards in this dataset)?
df %>%
  select(birthplace, award) %>%
  separate(birthplace, c("city", "country_state"), sep = ",") %>%
  count(country_state, sort = TRUE, na.rm = T) %>%
  mutate(country_state = fct_reorder(country_state, n)) %>%
  ggplot(aes(n, country_state)) +
  geom_col()
```




```{r}
# creating dummy vars for gender
df$men <- ifelse(df$award == "Best Supporting Actor" | df$award == "Best Actor", 1,0)

df$women <- ifelse(df$award == "Best Supporting Actress" | df$award == "Best Actress", 1, 0)

df2 <- df %>%
  separate(date_of_birth, into = c("day", "month", "birth_year"), sep = "-")


# this creates year 2000 instead of 1900:  im lost .....
df$new_date <- lubridate::parse_date_time(df$date_of_birth,
                           orders = "d m y"
                           )

df %>%
  mutate(date_b = as.character(date_of_birth),
         new_date = as.character(new_date)) %>%
  select(date_of_birth, new_date, date_b)
```



```{r}
# confidence intervals

df$not_white <- ifelse(df$race_ethnicity != "White", 1, 0)

bt <- df %>%
  select(race_ethnicity, award, not_white) %>%
  specify(response = not_white) %>%
  generate(reps = 1000, type = "bootstrap") %>%
  calculate(stat = "mean")

pct <- bt %>% get_confidence_interval(level = 0.95, type = "percentile")

ggplot(bt, aes(stat)) +
  geom_bar(position = "dodge" ) +
  shade_confidence_interval(endpoints = pct) +
  ggtitle("Average of non white oscar winners") +
  scale_x_continuous(labels = scales::percent_format())
```